### ISSUE TITLE
Installation succeeds and then fails

### ISSUE THREAD

**Issue by riehemr** [emichael/texthings#11]
I installed and succeeded in using TeXAllThings this morning.  By the afternoon it failed.  Pulling up the same post.  This was done on Facebook.  I was using the same machine, OS, and browser.  I looked at the same post and the code had not been executed but was still the same.

**Comment by emichael** [comment]
I'm not seeing any issues on Facebook right now. Did you change the settings, perhaps?

What context was the TeX in? I just tested it with a message, and everything was working fine.
