### ISSUE TITLE
TeX all the things doesn't work at all on Chrome Version 40.0.2214.111 (64-bit) for Mac.

### ISSUE THREAD

**Issue by 11Kilobytes** [emichael/texthings#12]
Steps to reproduce.
1) Get a mac
2) Download the latest google chrome and open it,
3) Install TeX all the things from the Chrome Web Store
4) Go on Faceboook and make a private post, $ 1 + 1 = 2$
5) Click on the "TeX" button next to the url bar

Expected output:
 Nicely typeset version of 1 + 1 = 2

Actual output:
$1 + 1 = 2$

**Comment by emichael** [comment]
Hi @11Kilobytes,

I couldn't reproduce the issue. Did you click the toolbar and get a greyed out icon? That disables the extension entirely, so perhaps that's what happened. Ordinarily, you don't have to do anything to get your LaTeX to be typeset.

**Comment by 11Kilobytes** [comment]
Never mind, I had a space between the dollar sign and the equation.

**Comment by emichael** [comment]
That shouldn't actually affect things.... Unless maybe it was a newline that became a <br>

**Comment by 11Kilobytes** [comment]
Nah, I was confused, I thought you had to _press_ the button to turn the plugin on, but in actuality it was the other way around.

**Comment by emichael** [comment]
Okay, good deal. Maybe I'll try to make it more clear.
