### ISSUE TITLE
Allow user-defined tags/commands

### ISSUE THREAD

**Issue by vinchuco** [emichael/texthings#20]
Example:
http://www.openproblemgarden.org/

Anything inside:
\begin{conjecture}
\begin{problem}
\begin{proof}
\...

Doesn't get prettified.

**Comment by emichael** [comment]
My guess is that MathJax doesn't have the necessary packages for the proof environment. Can you get a minimal example of the problem?

**Comment by vinchuco** [comment]
Minimal? 
http://www.openproblemgarden.org/op/turan_number_of_a_finite_family
Used here for instance

**Comment by emichael** [comment]
Yeah, the issue is that those environments aren't supported by MathJax; nothing I can do. A list of supported environments is [here](http://docs.mathjax.org/en/latest/tex.html#environments).

**Comment by vinchuco** [comment]
You're right! I didn't know MathJax
