### ISSUE TITLE
allow option to render latex inside of pre tags

### ISSUE THREAD

**Issue by connorjclark** [emichael/texthings#24]
This would be greatly useful!

Perhaps an additional field could be created in the options page, detailing the "skipTags" to pass onto MathJax. I provided a link detailing that:

https://groups.google.com/forum/#!topic/mathjax-users/LTFRmB3MJHI

If this change would be accepted, I'd be happy to do it myself.

**Comment by emichael** [comment]
Sure thing. This seems like a good thing to do, and I'd appreciate pull requests. Ideally, you should also be able to set this option on a per-domain basis.

**Comment by connorjclark** [comment]
Great. I'll include your suggestion. Should get to it sometime next week.
