### ISSUE TITLE
Rendering expectation sign

### ISSUE THREAD

**Issue by jacekplocharczyk** [emichael/texthings#30]
Hi. I'm trying to render expectation sign ( this way \mathop{\mathbb{E}} ).

Can I set this somehow by the options tab or is it impossible at the moment?

Example of sign:
![image](https://user-images.githubusercontent.com/41325597/65416433-11b1be80-ddf8-11e9-95d8-624f0606ae99.png)

Thanks
Jacek

**Comment by emichael** [comment]
[;  \mathop{\mathbb{E}} ;]

Works for me. Are you getting other latex to render? Are you seeing any errors in the console?

**Comment by jacekplocharczyk** [comment]
Hi,
I don't know what console are you talking about but for example my notes [here](https://github.com/jacekplocharczyk/ml-notes/blob/master/cost_function.md) looks like that 
![image](https://user-images.githubusercontent.com/41325597/65595549-56bf2780-df95-11e9-82b2-f0ba981329f2.png)


And your sign is working as well.

**Comment by pkra** [comment]
@jacekplocharczyk the underscores are converted to HTML i elements. This breaks MathJax processing since its parser will stop at HTML tags (for sanity reasons).

**Comment by emichael** [comment]
@pkra Good call.

@jacekplocharczyk On Github, you can escape its Markdown processing like this.

$$
J(\theta) = - \mathop{\mathbb{E}}\ \_{x, y	\sim  \hat p\_{data}} \text{log} \ p\_{\text{model}}(y | x)
$$
