### ISSUE TITLE
Allow filtering of `div` classes as well as HTML tags

### ISSUE THREAD

**Issue by vegerot** [emichael/texthings#32]
The HTML tags option is great, but most things I'd like to blacklist are of `<div class="something args="otherthings"> stuff </div>`.  Would it be possible to allow blacklisting of these sorts of things?

**Comment by emichael** [comment]
That's a MathJax thing, unfortunately. Currently there's no way to exclude elements using general selectors.

http://docs.mathjax.org/en/latest/options/document.html
