### ISSUE TITLE
Telegram compatibility (add ignoreClass filter)

### ISSUE THREAD

**Issue by galashin** [emichael/texthings#35]
Me and my coauthor have been trying to get LaTeX to work with Telegram. Unfortunately, all elements on https://web.telegram.org/ are `div`'s (and of course it is very annoying and buggy when it renders LaTeX live as I type the message). So I just tweaked `pageScript.js` a little bit by adding the ` ignoreClass: ["composer_rich_textarea"]` line to `tex2jax`. In general, it would be very useful to add class selectors to the settings page.

**Comment by emichael** [comment]
Fixed by #36.
